jobs:
- job: Build
  strategy:
    matrix:
      GoWin:
        OS_PLATFORM: 'windows-latest'
        EXECUTABLE_NAME: 'shanty_windows_x64.exe'
      GoMac:
        OS_PLATFORM: 'macOS-latest'
        EXECUTABLE_NAME: 'shanty_darwin_x64'
      GoLinux:
        OS_PLATFORM: 'ubuntu-latest'
        EXECUTABLE_NAME: 'shanty_linux_x64'
    maxParallel: 1
  pool:
    vmImage: $(OS_PLATFORM)
  steps:
    - script: go build -v -o $(Build.ArtifactStagingDirectory)/$(EXECUTABLE_NAME) shanty.go
      displayName: 'Build'
      
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'   
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-v')   
  inputs:
    gitHubConnection: bkief
    repositoryName: bkief/shanty          
    assets: $(Build.ArtifactStagingDirectory)/shanty*
